version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_service_test
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5

  integration-tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      TEST_DATABASE_URL: "postgres://postgres:postgres@postgres:5432/app_service_test?sslmode=disable"
      STORAGE_ENDPOINT: "minio:9000"
      STORAGE_ACCESS_KEY: "minioadmin"
      STORAGE_SECRET_KEY: "minioadmin"
      STORAGE_USE_SSL: "false"
    env_file:
      - .env.test
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy 