FROM golang:1.22-alpine

# Install build dependencies
RUN apk add --no-cache git curl build-base

# Set working directory
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy source code
COPY . .

# TODO: Uncomment when sqlc is used
# # Install sqlc
# RUN go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest

# # Generate code
# RUN sqlc generate

# Run tests
CMD ["go", "test", "-v", "./...", "-tags=integration"] 