apiVersion: v1
kind: ConfigMap
metadata:
  name: rso-config
  namespace: rso
data:
  ENVIRONMENT: "production"
  # Postgres connection (internal DNS v Azure)
  DB_HOST: "rso-prod-psql.postgres.database.azure.com"
  DB_PORT: "5432"
  DB_USER: "psqladmin"
  DB_NAME: "rso"
  # Service endpoints
  AUTH_SERVICE_URL: "http://auth-service:8080"
  PAYMENT_SERVICE_URL: "http://payment-service:8080"
  REVIEWS_SERVICE_URL: "http://reviews-service:8080"
  APP_SERVICE_URL: "http://app-service:8080" 