apiVersion: v1
kind: Secret
metadata:
  name: rso-secrets
  namespace: rso
type: Opaque
data:
  # Auth service secrets
  JWT_SECRET: ${base64encode(jwt_secret)}
  AUTH0_CLIENT_ID: ${base64encode(auth_AUTH0_CLIENT_ID)}
  AUTH0_CLIENT_SECRET: ${base64encode(auth_AUTH0_CLIENT_SECRET)}
  
  # Database secrets
  POSTGRES_PASSWORD: ${base64encode(postgresql_password)}
  
  # Reviews service secrets
  REVIEWS_DATABASE_URL: ${base64encode(reviews_DATABASE_URL)}
  
  # App service secrets
  DATABASE_URL: ${base64encode(app_DATABASE_URL)}
  STORAGE_SECRET_KEY: ${base64encode(app_STORAGE_SECRET_KEY)} 