apiVersion: v1
kind: Secret
metadata:
  name: rso-secrets
  namespace: rso
type: Opaque
data:
  # TO-DO: Zamenjajte z dejanskimi vrednostmi (base64 encoded)
  DB_PASSWORD: "SDFzaDFDb1IzIQ==" # H@sh1CoR3! (spremenite to!)
  JWT_SECRET: "c3VwZXJzZWNyZXQ=" # supersecret (spremenite to!) 