name: Deploy API Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'app-service/gen/app/v1/**'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Generate Documentation
        working-directory: app-service/gen/app/v1
        run: bunx @redocly/cli build-docs app.openapi.yaml -o out/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'app-service/gen/app/v1/out/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
