name: 'Reviews: Build and Push to GitHub Container Registry'

permissions:
  # attestations: write
  contents: read
  packages: write

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'reviews/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        id: push
        with:
          context: ./reviews
          file: reviews/docker/Dockerfile
          push: true
          tags: ghcr.io/rso-ekipa-08/reviews:latest
      
      # - name: Generate artifact attestation
      #   uses: actions/attest-build-provenance@v2
      #   with:
      #     subject-name: ghcr.io/rso-ekipa-08/reviews
      #     subject-digest: ${{ steps.push.outputs.digest }}
      #     push-to-registry: true